/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHelsinki,
  IHelsinkiInterface,
} from "../../../contracts/Helsinki.sol/IHelsinki";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "security",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "tenure",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "safeAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "slope",
        type: "uint256",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHelsinki__factory {
  static readonly abi = _abi;
  static createInterface(): IHelsinkiInterface {
    return new Interface(_abi) as IHelsinkiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IHelsinki {
    return new Contract(address, _abi, runner) as unknown as IHelsinki;
  }
}
